// Next JS Imports
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

// CSS Imports
import './globals.css';

// Component Imports
import HeaderMobile from '@/components/header-mobile';
import { ThemeProvider } from '@/components/theme-provider';
import LeftSideNav from '@/components/left-side-nav';
import RightSideNav from '@/components/right-side-nav';
import PageWrapper from '@/components/page-wrapper';
import MarginWidthWrapper from '@/components/margin-width-wrapper';

// Lib Imports
import { cn } from '@/lib/utils';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      suppressHydrationWarning={true}
    >
      <body
        className={cn(inter.className, 'bg-[#F6F6F6]')}
        suppressHydrationWarning={true}
      >
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          <div className='flex'>
            <LeftSideNav />
            <main
              className={cn(
                'lg:w-[72dvw] md:w-[78dvw] w-[100dvw] lg:m-[unset] m-auto',
              )}
            >
              <MarginWidthWrapper>
                <HeaderMobile />
                <PageWrapper>{children}</PageWrapper>
              </MarginWidthWrapper>
            </main>
            <RightSideNav />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
