// Next JS Imports
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

// CSS Imports
import './globals.css';

// Component Imports
import MobileHeader from '@/components/header-mobile';
import { ThemeProvider } from '@/components/theme-provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          <MobileHeader />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
